sf RNs: March 27
forcedotcom/cli pull request #2790
Opened 2024-03-22 21:55 UTC by jshackell-sfdc

2024-03-26 13:54 UTC, cristiand391 approved these changes

2024-03-27 14:50 UTC, mshanemc approved these changes

2024-03-27 15:26 UTC, mdonnalley requested changes

2024-03-27 15:26 UTC, mdonnalley commented on releasenotes/README.md
> +     * If you run the command with both `--flags-dir` and `--json`, then the file names must have the `.json` extension, such as `metadata.json`.  Otherwise, the files don't have an extension.
You can use `--json` in conjunction with extension-less files

The `.json` extension is only required if the contents of the file are json

2024-03-27 18:20 UTC, merged